"""empty message

Revision ID: 9b3511a5b2d3
Revises: 
Create Date: 2024-11-29 02:41:51.201433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3511a5b2d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('residence_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('smoking_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stroke', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('stroke')
        batch_op.drop_column('smoking_status')
        batch_op.drop_column('residence_type')
        batch_op.drop_column('work_type')

    # ### end Alembic commands ###
